import { PACKAGE_BOUNDARY as CONTRACTS_PACKAGE_BOUNDARY } from '@medifind/contracts';

export const PACKAGE_BOUNDARY = 'api' as const;
export const CONTRACTS_BOUNDARY_REFERENCE = CONTRACTS_PACKAGE_BOUNDARY;
